// Icons
export * from './icons/mail'
export * from './icons/linkedin'
export * from './icons/add'
export * from './icons/remove'
export * from './icons/usability'
export * from './icons/sketching'
export * from './icons/iteration'
export * from './icons/prototyping'
export * from './icons/assistant'
export * from './icons/heart-user'
export * from './icons/microfone'
export * from './icons/workload'
export * from './icons/goal'
export * from './icons/denied'
export * from './icons/star'

// Components
export * from './hero-photo/hero-photo'
export * from './hero-section/hero-section'
export * from './skills-section/skills-section'
export * from './handle-reducing-teacher-workload/handle-reducing-teacher-workload'
export * from './handle-recovering-pre-pandemic/handle-recovering-pre-pandemic'
export * from './tags/tags'
export * from './button/button'
